apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-challenge-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: country-challenge-backend
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: country-challenge-backend  
    spec:     # pod spec                  
      containers: 
      - name: country-challenge-backend
        image: country-challenge-backend:latest # image we pushed
        imagePullPolicy: Never
        ports:
        - containerPort: 3001